<<<<<<< HEAD
version: "2"

services:configs:
  ruby:
    image: mdsn/1811
    ports:
      - 8080:8080
    environment:
      - TEXT=FIRST
  ruby2:
    image: mdsn/1811
    ports:
      - 8081:8080
    environment:
      - TEXT=SECOND
=======
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

volumes:
  wordpress:
>>>>>>> 020e968eb2adb36dec2645cb5325fb5785106227
